kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/cuisongliu/lxcfs-build/

steps:
  - name: publish-fist
    image: plugins/docker
    settings:
      repo: cuisongliu/lxcfs-build
      tags: ${DRONE_TAG=latest}
      username:
        from_secret: docker-hub-user
      dockerfile: Dockerfile
      password:
        from_secret: docker-hub-pass
    when:
      event:
        - push
